### ISSUE TITLE
Set up User List page

### ISSUE THREAD

**Issue by edaleeta** [hb-kada/hb-ratings#6]
It will list users with email addresses and user ids, like this:

- jessica@gmail.com (455)
- jane@gmail.com (900)

- Create Route ('/users')
- Set up Template

http://fellowship.hackbrightacademy.com/materials/f20a/exercises/ratings/index-2.html

**Comment by kvinton** [comment]
Done. Pull request coming soon. Will need to test tomorrow because I was having trouble with my /env in vagrant.
